language: cpp
os: linux
sudo: required
dist: trusty
compiler:
  - gcc
before_install:
  - sudo apt-get install gfortran -y
  - type gfortran
install: autoreconf -i && ./configure && make -j8 && make check -j8
after_failure:
  - cat test/test_results.txt
