language: cpp
os: linux
sudo: required
dist: trusty
compiler:
  - gcc
before_install:
  - sudo apt-get install gfortran -y
  - type gfortran
install: autoreconf -i && ./configure && make && make check
script:
  - cd test && ./run_test.sh
